version: '2.1'
orbs: 
  node: circleci/node@5.0.2
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    working_directory: '~/repo'
    steps:
      - checkout
      # Download and Cache dependency
        
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: yarn ng build --prod
      - run: yarn ng test --single-run
workflows:
  test_my_app:
    jobs:
      - install-node-example